services:

  app:
    build: .
    container_name: libswap-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/libswap
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      STUDENT_NAME: ${STUDENT_NAME}
      STUDENT_ID: ${STUDENT_ID}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: libswap-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: